server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Aquariums Service
        - id: aquariums-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/aquariums/**
          
        # Inhabitants Service
        - id: inhabitants-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/aquariums/*/inhabitants/**
            
        # Species Service
        - id: species-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/species/**
            
        # Maintenance Service
        - id: maintenance-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/aquariums/*/maintenance/**
            
        # Water Parameters Service
        - id: water-parameters-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/water-parameters/**
            
        # Manual Parameters Service
        - id: manual-parameters-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/manual-parameters/**
            
        # Target Parameters Service
        - id: target-parameters-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/target-parameters/**
      
      # Configurazione CORS globale
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
